version: "3"
services:
  salvatorelaspata.net:
    ports:
      - "4321:4321"
    restart: always
    container_name: salvatorelaspata.net
    # platform: linux/amd64
    image: salvatorela/salvatorelaspata.net
